import type { EnvironmentProfile } from './types';

const sharedProductionRestrictions = [
  'delete',
  'remove',
  'checkout',
  'payment',
  'send-email',
  'send-message',
  'purge',
  'reset-password',
  'account-settings-change',
];

export const environmentProfiles: Record<string, EnvironmentProfile> = {
  local: {
    id: 'local',
    name: 'Local',
    baseUrl: 'http://localhost:3000',
    loginUrl: 'http://localhost:3000/login',
    featureFlags: { betaDashboard: true, newCheckout: true },
    allowedDomains: ['localhost', '127.0.0.1'],
    restrictedActions: [],
    apiEnvironment: 'local',
    locale: 'en-US',
    timezone: 'UTC',
    testDataMode: 'synthetic',
    riskTier: 'low',
    allowDataMutation: true,
    allowDestructiveActions: true,
    allowEmailSending: false,
  },
  dev: {
    id: 'dev',
    name: 'Development',
    baseUrl: 'https://dev.example.com',
    loginUrl: 'https://dev.example.com/login',
    featureFlags: { betaDashboard: true, newCheckout: true, experimentalSearch: true },
    allowedDomains: ['dev.example.com'],
    restrictedActions: ['send-email', 'send-message'],
    apiEnvironment: 'dev',
    locale: 'en-US',
    timezone: 'UTC',
    testDataMode: 'synthetic',
    riskTier: 'low',
    allowDataMutation: true,
    allowDestructiveActions: true,
    allowEmailSending: false,
  },
  qa: {
    id: 'qa',
    name: 'QA',
    baseUrl: 'https://qa.example.com',
    loginUrl: 'https://qa.example.com/login',
    featureFlags: { betaDashboard: true, newCheckout: false },
    allowedDomains: ['qa.example.com'],
    restrictedActions: ['send-email'],
    apiEnvironment: 'qa',
    locale: 'en-GB',
    timezone: 'Europe/London',
    testDataMode: 'fixture',
    riskTier: 'medium',
    allowDataMutation: true,
    allowDestructiveActions: false,
    allowEmailSending: false,
  },
  uat: {
    id: 'uat',
    name: 'UAT',
    baseUrl: 'https://uat.example.com',
    loginUrl: 'https://uat.example.com/login',
    featureFlags: { betaDashboard: false, newCheckout: true },
    allowedDomains: ['uat.example.com'],
    restrictedActions: ['delete', 'purge', 'send-email', 'send-message'],
    apiEnvironment: 'uat',
    locale: 'en-US',
    timezone: 'America/New_York',
    testDataMode: 'shared',
    riskTier: 'medium',
    allowDataMutation: true,
    allowDestructiveActions: false,
    allowEmailSending: false,
  },
  staging: {
    id: 'staging',
    name: 'Staging',
    baseUrl: 'https://staging.example.com',
    loginUrl: 'https://staging.example.com/login',
    featureFlags: { betaDashboard: false, newCheckout: false },
    allowedDomains: ['staging.example.com'],
    restrictedActions: [...sharedProductionRestrictions],
    apiEnvironment: 'staging',
    locale: 'en-US',
    timezone: 'America/New_York',
    testDataMode: 'readonly',
    riskTier: 'high',
    allowDataMutation: false,
    allowDestructiveActions: false,
    allowEmailSending: false,
  },
  'production-like': {
    id: 'production-like',
    name: 'Production-like',
    baseUrl: 'https://app.example.com',
    loginUrl: 'https://app.example.com/login',
    featureFlags: { betaDashboard: false, newCheckout: false },
    allowedDomains: ['app.example.com'],
    restrictedActions: [...sharedProductionRestrictions, 'edit', 'update', 'save changes', 'submit'],
    apiEnvironment: 'production',
    locale: 'en-US',
    timezone: 'UTC',
    testDataMode: 'readonly',
    riskTier: 'high',
    allowDataMutation: false,
    allowDestructiveActions: false,
    allowEmailSending: false,
  },
};

export function getEnvironmentProfile(id: string) {
  return environmentProfiles[id] || environmentProfiles.local;
}
