import type { PersonaProfile } from './types';

export const personaProfiles: Record<string, PersonaProfile> = {
  'first-time-user': {
    id: 'first-time-user',
    name: 'First-time user',
    description: 'New visitor exploring onboarding, signup, and introductory flows.',
    explorationPriorities: ['navigation', 'authentication', 'forms', 'search', 'accessibility'],
    riskProfile: 'conservative',
    preferredFlows: ['signup', 'register', 'welcome', 'onboarding', 'tutorial', 'get started'],
    permissions: ['read', 'signup'],
    restrictedFlows: ['admin', 'billing', 'delete', 'settings-change'],
    accessibilitySettings: { auditEnabled: true, keyboardCheckEnabled: true },
    navigationStyle: 'breadth-first',
  },
  'returning-user': {
    id: 'returning-user',
    name: 'Returning user',
    description: 'Authenticated user revisiting dashboard, orders, and saved content.',
    explorationPriorities: ['navigation', 'search', 'forms', 'state-persistence', 'filters'],
    riskProfile: 'balanced',
    preferredFlows: ['dashboard', 'orders', 'profile', 'recent', 'saved', 'history'],
    permissions: ['read', 'write'],
    restrictedFlows: ['admin', 'delete'],
    accessibilitySettings: { auditEnabled: true, keyboardCheckEnabled: false },
    navigationStyle: 'task-focused',
  },
  admin: {
    id: 'admin',
    name: 'Admin',
    description: 'Privileged operator exploring management, settings, and configuration areas.',
    explorationPriorities: ['settings', 'navigation', 'forms', 'create-edit-delete', 'filters'],
    riskProfile: 'balanced',
    preferredFlows: ['settings', 'admin', 'manage', 'users', 'roles', 'configuration', 'audit'],
    permissions: ['read', 'write', 'admin'],
    restrictedFlows: [],
    accessibilitySettings: { auditEnabled: true, keyboardCheckEnabled: true },
    navigationStyle: 'depth-first',
  },
  'readonly-user': {
    id: 'readonly-user',
    name: 'Read-only user',
    description: 'Viewer with read access only; edit and mutation flows should be avoided.',
    explorationPriorities: ['navigation', 'search', 'filters', 'accessibility', 'console-network'],
    riskProfile: 'conservative',
    preferredFlows: ['view', 'report', 'dashboard', 'search', 'export'],
    permissions: ['read'],
    allowedActions: ['navigate', 'click', 'search', 'select', 'goBack', 'wait', 'waitForLoadState', 'screenshot', 'noop', 'stop'],
    restrictedFlows: ['edit', 'save', 'delete', 'update', 'submit', 'create', 'upload', 'settings-change'],
    accessibilitySettings: { auditEnabled: true, keyboardCheckEnabled: true },
    navigationStyle: 'breadth-first',
  },
  'premium-user': {
    id: 'premium-user',
    name: 'Premium user',
    description: 'Paid subscriber exploring premium-only features and upgrade paths.',
    explorationPriorities: ['navigation', 'forms', 'search', 'settings', 'state-persistence'],
    riskProfile: 'balanced',
    preferredFlows: ['premium', 'upgrade', 'subscription', 'billing', 'pro', 'exclusive'],
    permissions: ['read', 'write', 'premium'],
    restrictedFlows: ['admin', 'delete'],
    accessibilitySettings: { auditEnabled: true, keyboardCheckEnabled: false },
    navigationStyle: 'task-focused',
  },
  'mobile-only-user': {
    id: 'mobile-only-user',
    name: 'Mobile-only user',
    description: 'Mobile-first visitor; responsive layout and compact navigation are prioritized.',
    explorationPriorities: ['responsiveness', 'navigation', 'search', 'forms', 'accessibility'],
    riskProfile: 'conservative',
    preferredFlows: ['menu', 'hamburger', 'mobile', 'app', 'touch'],
    permissions: ['read', 'write'],
    restrictedFlows: [],
    accessibilitySettings: { auditEnabled: true, keyboardCheckEnabled: true },
    navigationStyle: 'breadth-first',
    viewport: { width: 390, height: 844 },
  },
  'accessibility-user': {
    id: 'accessibility-user',
    name: 'Accessibility user',
    description: 'Assistive-technology user prioritizing keyboard, contrast, and screen-reader paths.',
    explorationPriorities: ['accessibility', 'navigation', 'forms', 'search'],
    riskProfile: 'conservative',
    preferredFlows: ['accessibility', 'contrast', 'keyboard', 'skip', 'screen reader', 'aria'],
    permissions: ['read'],
    restrictedFlows: ['checkout', 'payment'],
    accessibilitySettings: { auditEnabled: true, keyboardCheckEnabled: true },
    navigationStyle: 'breadth-first',
  },
  'anonymous-visitor': {
    id: 'anonymous-visitor',
    name: 'Anonymous visitor',
    description: 'Unauthenticated guest exploring marketing, signup, login, and paywall flows.',
    explorationPriorities: ['authentication', 'navigation', 'search', 'forms', 'accessibility'],
    riskProfile: 'conservative',
    preferredFlows: ['sign in', 'log in', 'register', 'pricing', 'paywall', 'trial', 'demo'],
    permissions: ['read', 'signup'],
    restrictedFlows: ['admin', 'settings', 'delete', 'billing'],
    accessibilitySettings: { auditEnabled: true, keyboardCheckEnabled: true },
    navigationStyle: 'breadth-first',
  },
};

export function getPersonaProfile(id: string) {
  return personaProfiles[id] || personaProfiles['anonymous-visitor'];
}
