import type { ExplorationConfig } from '../types';

export const defaultExplorationConfig: ExplorationConfig = {
  baseUrl: 'https://www.amazon.co.uk',
  environmentName: 'production-like',
  environmentId: 'production-like',
  personaId: 'anonymous-visitor',
  locale: 'en-GB',
  timezone: 'Europe/London',
  maxSteps: 10,
  maxDurationMinutes: 5,
  viewport: {
    width: 1440,
    height: 900,
  },
  persona: 'anonymous-visitor',
  allowedDomains: ['amazon.co.uk', 'www.amazon.co.uk', 'amazon.com', 'www.amazon.com', 'localhost', '127.0.0.1'],
  allowedActions: [
    'navigate',
    'click',
    'fill',
    'search',
    'select',
    'check',
    'uncheck',
    'press',
    'goBack',
    'wait',
    'waitForLoadState',
    'screenshot',
    'noop',
    'stop',
  ],
  forbiddenActions: [
    'checkout',
    'payment',
    'send-email',
    'send-message',
    'delete',
    'account-settings-change',
  ],
  stopConditions: [
    'maxSteps',
    'maxDuration',
    'criticalFinding',
    'maxCriticalFailures',
    'loopDetected',
    'noMeaningfulActions',
    'riskyActionRequiresPermission',
    'userDefined',
  ],
  evidenceDirectory: 'exploratory-results/evidence',
  reportingOptions: {
    reportDirectory: 'exploratory-results',
    includeConsole: true,
    includeNetwork: true,
    includeScreenshots: true,
  },
  screenshotMode: 'on-failure',
  saveVideo: false,
  generateTests: true,
  accessibilityAuditEnabled: true,
  keyboardNavigationCheckEnabled: true,
  networkIntelligenceEnabled: true,
  networkSlowWarnMs: 1000,
  networkSlowHighMs: 3000,
  networkSlowCriticalMs: 8000,
  visualIntelligenceEnabled: true,
  multiViewportVisualMode: false,
  visualComparisonEnabled: true,
  visualDiffThreshold: 0.1,
  reasoningEnabled: true,
  llmProvider: 'gemini',
  llmModel: 'gemini-2.0-flash',
  maxReasoningContextChars: 1200,
  visionMultimodalEnabled: false,
  visionProvider: 'mock',
  visionMode: 'batched',
  visionCacheEnabled: true,
  visionAnnotateScreenshots: true,
  visionBatchSize: 2,
  visionMaxScreenshotsPerSession: 12,
  recoveryEnabled: false,
  maxRetriesPerAction: 3,
  maxRecoveryAttemptsPerSession: 15,
  maxSelectorHealingAttempts: 8,
  learningEnabled: false,
  longTermMemoryPath: 'exploratory-results/long-term-memory/knowledge.json',
  learningStorageAdapter: 'json',
  multiAgentEnabled: true,
  multiAgentScheduleMode: 'parallel',
  multiAgentFocus: 'full',
  multiAgentEscalateCritical: true,
  multiAgentRunTestGenerator: true,
};
